version: "3.7"
services:
  outline-client:
    image: ghcr.io/jigsaw/outline-client@sha256:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  # Укажите digest для образа
    container_name: ${APP_ID}_app
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data:/data
    ports:
      - "${APP_PORT}:3000"  # Порт для веб-интерфейса
    environment:
      - OUTLINE_SERVER_HOST=${OUTLINE_SERVER_HOST}  # Переменная для указания адреса Outline сервера
